# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --watchAll=false
